# Standard settings
SET(CMAKE_SYSTEM_NAME Darwin)
SET(CMAKE_SYSTEM_VERSION 11)
SET(CMAKE_SYSTEM_PROCESSOR arm-apple)
set (UNIX True)
#set (APPLE True)
set (IOS True)

set(CMAKE_CROSSCOMPILING True)

SET(CMAKE_C_COMPILER /usr/local/bin/ios-clang)
SET(CMAKE_CXX_COMPILER /usr/local/bin/ios-clang++)
SET(_CMAKE_TOOLCHAIN_PREFIX arm-apple-darwin11-)

SET(CMAKE_FIND_ROOT_PATH /Developer/iOS/sysroot)

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(CMAKE_LINK_LIBRARY_SUFFIX "")
SET(CMAKE_FIND_LIBRARY_PREFIXES "lib")
SET(CMAKE_STATIC_LIBRARY_PREFIX "lib")
SET(CMAKE_STATIC_LIBRARY_SUFFIX ".a")
SET(CMAKE_SHARED_LIBRARY_PREFIX "lib")          # lib
SET(CMAKE_SHARED_LIBRARY_SUFFIX ".dylib")           # .a
set(CMAKE_SHARED_MODULE_PREFIX "lib")
set(CMAKE_SHARED_MODULE_SUFFIX ".so")
set(CMAKE_MODULE_EXISTS 1)
SET(CMAKE_EXECUTABLE_SUFFIX "")          # .exe
SET(CMAKE_DL_LIBS "" )
SET(CMAKE_FIND_LIBRARY_PREFIXES "lib")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".dylib" ".so" ".a")



SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -march=armv7s -objc-arc -fblocks -g0 -O2 -DIOS")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -objc-arc -fblocks -g0 -O2 -DIOS")
SET(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "")
SET(CMAKE_C_LINK_EXECUTABLE "")
SET(CMAKE_CXX_LINK_EXECUTABLE "")

add_definitions(-DIOS)
